import firebase_admin
from firebase_admin import credentials
from firebase_admin import auth
from firebase import firebase
import base64
import jwt

#Este es el modulo para probar el token de la app en android
cred = credentials.Certificate('credentialtest.json')
firebase_admin.initialize_app(cred, {
    "apiKey": "AIzaSyAWVcK8FQHJ5mnGZOPj5MBLQXXSr9PndKM",
    "authDomain": "labcompumovilvl.firebaseapp.com",
    "databaseURL": "https://labcompumovilvl.firebaseio.com",
    "storageBucket": "labcompumovilvl.appspot.com"
})


token = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjQ3NjA3YWVhMDdlOTQzNzA1MTdhNjEyNmExODRkMTI3MmE2OTY1OTEifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbGFiY29tcHVtb3ZpbHZsIiwibmFtZSI6IlNhbmRyYSBWaXZpYW5hIExvbmRvw7FvIENvcnTDqXMiLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDYuZ29vZ2xldXNlcmNvbnRlbnQuY29tLy10eUlUdFNyYWYwYy9BQUFBQUFBQUFBSS9BQUFBQUFBQUFBQS9BTlEwa2Y1Uy1sblZ5dVJmRmtqTmpvODZGT21XcDg2N0pRL3M5Ni1jL3Bob3RvLmpwZyIsImF1ZCI6ImxhYmNvbXB1bW92aWx2bCIsImF1dGhfdGltZSI6MTUxMTYwMzUyNCwidXNlcl9pZCI6IjNwQWhhZmlaTDhVRTNMem1WT3JqdVoxc3FZbDIiLCJzdWIiOiIzcEFoYWZpWkw4VUUzTHptVk9yanVaMXNxWWwyIiwiaWF0IjoxNTExNjAzNTI0LCJleHAiOjE1MTE2MDcxMjQsImVtYWlsIjoic3ZpdmlhbmFsb25kb25vQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7Imdvb2dsZS5jb20iOlsiMTAwMTMzNjE0MDcxNTIyOTIxMDk1Il0sImVtYWlsIjpbInN2aXZpYW5hbG9uZG9ub0BnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJnb29nbGUuY29tIn19.ZffEbJNTNMv9aSTdXcQoCM8fPoRDVG8wT94ToPenuVFSEg_Z7UeP_Zo3bSjsNeyjh8vDQPijvhHVMHBlaY_dRBghrHuvsIoCYgmV-PFpEC0zzt0OQC55EpYsC3425K5rueg3vaECWpmRhEoeTACThK58h-Yux7PpPJ79B2UsqRcxf7w6iIEx_lbwSfgv4x4E69OyU5G_1qD9HfDDqn7z23pepijtZgS5WJf5RrfzJoIJ_ni4OSJC_PcBQQ2RluUanvcWWo5gWydicilZTKwNE2JL5QzD90QDEHYm5-c2nfcQONkehDc7IA1OWYdH9H-Fbw9nhOFKqPmf8vwFa4O0LA"
decoded_token = auth.verify_id_token(token)
email = decoded_token['email']
print(email)